In [42]:
import numpy as np
import math
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split

The Cell containing all the imports I need

In [43]:
iris = load_iris()
X_train, X_test, Y_train, Y_test = train_test_split(iris['data'], 
    iris['target'], random_state=2705)

IoData = np.genfromtxt("ionosphere.txt", delimiter=",", usecols=np.arange(34))
IoLabel = np.genfromtxt("ionosphere.txt", delimiter=",",usecols=34, dtype='int')
IoX_train, IoX_test, IoY_train, IoY_test = train_test_split(IoData, 
    IoLabel, random_state=2705)

The cell that imports the ionosphere text file and splits both the text file and iris into sets

In [34]:
print(IoX_train)

[[ 1.       0.      -0.65625 ...  0.       0.       0.09375]
 [ 1.       0.       0.95559 ... -0.01957  0.78761 -0.02039]
 [ 1.       0.       0.83427 ...  0.70011 -0.03983  0.79444]
 ...
 [ 1.       0.       0.98002 ...  0.08126  0.97247  0.08616]
 [ 0.       0.       0.      ...  1.       0.       0.     ]
 [ 1.       0.       0.88103 ... -0.18542  0.91747 -0.16827]]


In [33]:
print(IoX_test)

[[ 1.       0.       0.82624 ...  0.18085  0.92553  0.     ]
 [ 1.       0.       1.      ... -0.92128 -0.13341 -1.     ]
 [ 1.       0.       0.79378 ... -0.23199  0.34572 -0.08036]
 ...
 [ 1.       0.       1.      ...  0.10067  1.       0.10067]
 [ 1.       0.       1.      ... -0.47977  0.75115 -0.50152]
 [ 1.       0.       0.84713 ... -0.37792  0.65817 -0.24841]]


In [6]:
print(IoY_train)

[-1  1  1  1  1 -1 -1  1 -1  1 -1  1 -1  1  1 -1 -1 -1  1  1 -1  1  1 -1
  1  1 -1  1 -1 -1  1  1  1  1  1  1  1  1  1  1 -1  1  1 -1  1  1 -1 -1
  1  1 -1  1  1  1  1 -1  1  1  1  1  1 -1  1  1  1  1  1  1  1  1 -1 -1
 -1  1  1  1  1  1 -1  1  1  1 -1 -1 -1  1 -1 -1  1  1  1  1  1 -1  1  1
  1  1 -1  1 -1  1  1  1  1  1  1 -1 -1  1  1 -1  1 -1 -1  1  1  1 -1  1
 -1  1 -1 -1  1  1  1  1 -1  1 -1 -1  1 -1  1 -1  1  1 -1  1  1  1 -1  1
  1 -1  1  1  1  1  1  1  1  1  1 -1  1  1 -1  1  1 -1  1  1 -1 -1 -1  1
  1  1  1 -1  1 -1  1  1  1  1  1  1  1 -1  1  1 -1 -1  1 -1  1  1 -1  1
  1  1  1 -1 -1  1 -1  1 -1 -1 -1  1  1  1  1  1  1  1  1  1 -1  1 -1 -1
  1  1 -1 -1 -1  1  1  1  1  1  1  1  1 -1  1 -1 -1 -1  1 -1  1 -1 -1  1
  1  1  1 -1  1  1 -1 -1  1  1 -1  1 -1  1 -1  1  1 -1  1  1  1 -1  1]


In [42]:
print(Y_test)

[0 0 2 0 0 2 1 2 2 1 1 2 0 1 0 2 1 0 2 1 1 1 1 2 1 0 2 1 2 1 1 0 2 1 0 1 2
 2]


In [54]:
#Xtest = IoX_test 
#Xtrain = IoX_train 
#Ytest = IoY_test 
#Ytrain = IoY_train 

Xtest = X_test
Xtrain = X_train
Ytest = Y_test
Ytrain = Y_train

correct = 0
Pfalse = 0
values = np.unique(Ytest)
FalseConformity = []
Conformity = []
for i in range(len(Xtest)):   
    minimum = {}
    for k in range(len(values)):
        minimum[values[k]] = math.inf
    for j in range(len(Xtrain)):
        dotProduct = 0
        for n in range(len(Xtrain[j])):
            dotProduct = dotProduct + (Xtrain[j][n] - Xtest[i][n])**2
        dotProduct = dotProduct**0.5
        for key in minimum:
            if dotProduct < minimum.get(key) and key == Ytrain[j]:
                minimum[key] = dotProduct             
    firstMin = min(minimum, key=minimum.get)   
    if Ytest[i] == firstMin: 
        correct += 1
        lowest = minimum.get(firstMin)
        del minimum[firstMin]
        secondMin = min(minimum, key=minimum.get)
        Conformity.append(minimum.get(secondMin)/lowest)
        #Conformity.append(1/lowest)
    else:    
        FalseConformity.append(minimum.get(firstMin)/minimum.get(Ytest[i]))
        #FalseConformity.append(1/minimum.get(Ytest[i]))
for i in range(len(Conformity)):
    FalseConformity.append(Conformity[i])
for i in range(len(FalseConformity)-correct):
    rank = 1
    for j in range(len(FalseConformity)):
        if FalseConformity[i] < FalseConformity[j]:
            rank += 1
    Pfalse = Pfalse + rank/len(FalseConformity)
print("Percentage correct: ", (correct/len(Xtest))*100)
print("P-False value: ", 1-Pfalse/(len(Xtest)-correct))

Percentage correct:  94.73684210526315
P-False value:  0.013157894736842035


The cell containing the code for nearest neighbour and conformal predictor, alternate the comments to change which dataset is being used. IoX/IoY uses the ionosphere dataset and X/Y uses the iris dataset.
When using the conformity measure used in slide 15 of chapter 3, the P-False values grew both times due to the fact that 1 is ofter larger than the two lowest values in each dataset.